# Generated by Django 6.1.1 on 2026-09-23 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localGuide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='service_area',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
