# Generated by Django 6.1.1 on 2026-09-23 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tourist', '0002_assistancerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistancerequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assistancerequest',
            name='package_amount',
            field=models.PositiveIntegerField(default=500),
        ),
        migrations.AddField(
            model_name='assistancerequest',
            name='package_hours',
            field=models.PositiveSmallIntegerField(choices=[(2, '2 hours - Rs 500'), (4, '4 hours - Rs 900'), (8, '8 hours - Rs 1,600')], default=2),
        ),
    ]
